-- 1. 테이블 초기화 (항상 맨 앞에 추가, 종속성을 고려해 순서대로 삭제)
DROP TABLE IF EXISTS CAR_RENTAL_COMPANY_RENTAL_HISTORY;

DROP TABLE IF EXISTS CAR_RENTAL_COMPANY_DISCOUNT_PLAN;

DROP TABLE IF EXISTS CAR_RENTAL_COMPANY_CAR;

-- 2. 자동차 정보 테이블 생성 (모두 NOT NULL)
CREATE TABLE CAR_RENTAL_COMPANY_CAR (
    CAR_ID INTEGER NOT NULL,
    CAR_TYPE VARCHAR(255) NOT NULL,
    DAILY_FEE INTEGER NOT NULL,
    OPTIONS VARCHAR(255) NOT NULL
);

-- 3. 자동차 대여 기록 테이블 생성 (모두 NOT NULL)
CREATE TABLE CAR_RENTAL_COMPANY_RENTAL_HISTORY (
    HISTORY_ID INTEGER NOT NULL,
    CAR_ID INTEGER NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL
);

-- 4. 자동차 할인 정책 테이블 생성 (모두 NOT NULL)
CREATE TABLE CAR_RENTAL_COMPANY_DISCOUNT_PLAN (
    PLAN_ID INTEGER NOT NULL,
    CAR_TYPE VARCHAR(255) NOT NULL,
    DURATION_TYPE VARCHAR(255) NOT NULL,
    DISCOUNT_RATE INTEGER NOT NULL
);

-- 5. 데이터 삽입 (CAR_RENTAL_COMPANY_CAR)
INSERT INTO
    CAR_RENTAL_COMPANY_CAR (CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS)
VALUES
    (1, '트럭', 26000, '가죽시트,열선시트,후방카메라'),
    (2, 'SUV', 14000, '스마트키,네비게이션,열선시트'),
    (3, '트럭', 32000, '주차감지센서,후방카메라,가죽시트');

-- 6. 데이터 삽입 (CAR_RENTAL_COMPANY_RENTAL_HISTORY)
INSERT INTO
    CAR_RENTAL_COMPANY_RENTAL_HISTORY (HISTORY_ID, CAR_ID, START_DATE, END_DATE)
VALUES
    (1, 1, '2022-07-27', '2022-08-02'),
    (2, 1, '2022-08-03', '2022-08-04'),
    (3, 2, '2022-08-05', '2022-08-05'),
    (4, 2, '2022-08-09', '2022-08-12'),
    (5, 3, '2022-09-16', '2022-10-15');

-- 7. 데이터 삽입 (CAR_RENTAL_COMPANY_DISCOUNT_PLAN)
INSERT INTO
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN (PLAN_ID, CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE)
VALUES
    (1, '트럭', '7일 이상', 5),
    (2, '트럭', '30일 이상', 7),
    (3, '트럭', '90일 이상', 10),
    (4, '세단', '7일 이상', 5),
    (5, '세단', '30일 이상', 10),
    (6, '세단', '90일 이상', 15);

-- 8. 삽입된 데이터 최종 확인
SELECT
    *
FROM
    CAR_RENTAL_COMPANY_CAR;

SELECT
    *
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY;

SELECT
    *
FROM
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN;