-- 1. 테이블 초기화 (항상 맨 앞에 추가)
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;

-- 2. 저자 정보 테이블 생성 (PK 생략, 모두 NOT NULL)
CREATE TABLE AUTHOR (
    AUTHOR_ID INTEGER NOT NULL,
    AUTHOR_NAME VARCHAR(50) NOT NULL
);

-- 3. 도서 정보 테이블 생성 (PK 생략, 모두 NOT NULL)
CREATE TABLE BOOK (
    BOOK_ID INTEGER NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    AUTHOR_ID INTEGER NOT NULL,
    PRICE INTEGER NOT NULL,
    PUBLISHED_DATE DATE NOT NULL
);

-- 4. 데이터 삽입 (AUTHOR)
INSERT INTO AUTHOR (AUTHOR_ID, AUTHOR_NAME) VALUES
(1, '홍길동'),
(2, '김영호');

-- 5. 데이터 삽입 (BOOK)
INSERT INTO BOOK (BOOK_ID, CATEGORY, AUTHOR_ID, PRICE, PUBLISHED_DATE) VALUES
(1, '인문', 1, 10000, '2020-01-01'),
(2, '경제', 1, 9000, '2021-04-11'),
(3, '경제', 2, 11000, '2021-02-05');

-- 6. 삽입된 데이터 최종 확인
SELECT * FROM AUTHOR;
SELECT * FROM BOOK;