WITH SCORE AS (
    SELECT
        REST_ID,
        ROUND(AVG(REVIEW_SCORE), 2) SCORE
    FROM
        REST_REVIEW
    GROUP BY
        REST_ID
)
SELECT
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    S.SCORE SCORE
FROM
    REST_INFO I
    JOIN SCORE S ON I.REST_ID = S.REST_ID
WHERE
    I.ADDRESS LIKE '서울%'
ORDER BY
    S.SCORE DESC,
    I.FAVORITES DESC
SELECT
    I.REST_ID,
    I.REST_NAME,
    I.FOOD_TYPE,
    I.FAVORITES,
    I.ADDRESS,
    ROUND(AVG(R.REVIEW_SCORE), 2) SCORE
FROM
    REST_INFO I
    JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE
    I.ADDRESS LIKE '서울%'
GROUP BY
    I.REST_ID
ORDER BY
    SCORE DESC,
    I.FAVORITES DESC