-- 1. 테이블 초기화 (항상 맨 앞에 추가, 종속성을 고려해 대여 기록 테이블 먼저 삭제)
DROP TABLE IF EXISTS CAR_RENTAL_COMPANY_RENTAL_HISTORY;

DROP TABLE IF EXISTS CAR_RENTAL_COMPANY_CAR;

-- 2. 자동차 정보 테이블 생성 (PK 생략, 모두 NOT NULL)
CREATE TABLE CAR_RENTAL_COMPANY_CAR (
    CAR_ID INTEGER NOT NULL,
    CAR_TYPE VARCHAR(255) NOT NULL,
    DAILY_FEE INTEGER NOT NULL,
    OPTIONS VARCHAR(255) NOT NULL
);

-- 3. 자동차 대여 기록 테이블 생성 (PK 생략, 모두 NOT NULL)
CREATE TABLE CAR_RENTAL_COMPANY_RENTAL_HISTORY (
    HISTORY_ID INTEGER NOT NULL,
    CAR_ID INTEGER NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL
);

-- 4. 데이터 삽입 (CAR_RENTAL_COMPANY_CAR)
INSERT INTO
    CAR_RENTAL_COMPANY_CAR (CAR_ID, CAR_TYPE, DAILY_FEE, OPTIONS)
VALUES
    (1, '세단', 16000, '가죽시트,열선시트,후방카메라'),
    (2, 'SUV', 14000, '스마트키,네비게이션,열선시트'),
    (3, '세단', 22000, '주차감지센서,후방카메라,가죽시트'),
    (4, '세단', 12000, '주차감지센서');

-- 5. 데이터 삽입 (CAR_RENTAL_COMPANY_RENTAL_HISTORY)
INSERT INTO
    CAR_RENTAL_COMPANY_RENTAL_HISTORY (HISTORY_ID, CAR_ID, START_DATE, END_DATE)
VALUES
    (1, 4, '2022-09-27', '2022-09-27'),
    (2, 3, '2022-10-03', '2022-10-04'),
    (3, 2, '2022-10-05', '2022-10-05'),
    (4, 1, '2022-10-11', '2022-10-14'),
    (5, 3, '2022-10-13', '2022-10-15');

-- 6. 삽입된 데이터 최종 확인
SELECT
    *
FROM
    CAR_RENTAL_COMPANY_CAR;

SELECT
    *
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY;