-- 코드를 작성해주세요
WITH MAX_C AS(
    SELECT
        YEAR(DIFFERENTIATION_DATE) YEAR,
        MAX(SIZE_OF_COLONY) C
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR(DIFFERENTIATION_DATE)
)
SELECT
    YEAR(E.DIFFERENTIATION_DATE) YEAR,
    C.C - E.SIZE_OF_COLONY YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA E
    JOIN MAX_C C ON YEAR(E.DIFFERENTIATION_DATE) = C.YEAR
ORDER BY
    YEAR,
    YEAR_DEV;