SELECT
    CAR_ID,
    ROUND(AVG(DATEDIFF(END_DATE + 1, START_DATE)), 1) AVERAGE_DURATION
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY
    CAR_ID
HAVING
    AVG(DATEDIFF(END_DATE + 1, START_DATE)) >= 7
ORDER BY
    AVG(DATEDIFF(END_DATE + 1, START_DATE)) DESC,
    CAR_ID DESC;