SELECT
    B.PRODUCT_CODE,
    SUM(B.PRICE * A.SALES_AMOUNT) SALES
FROM
    OFFLINE_SALE A
    JOIN PRODUCT B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY
    B.PRODUCT_CODE
ORDER BY
    SUM(B.PRICE * A.SALES_AMOUNT) DESC,
    B.PRODUCT_CODE;