-- 코드를 입력하세요
SELECT
    B.CATEGORY,
    SUM(S.SALES) TOTAL_SALES
FROM
    BOOK_SALES S
    JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE
    S.SALES_DATE LIKE '2022-01%'
GROUP BY
    B.CATEGORY
ORDER BY
    B.CATEGORY;